version: '3.1'

services:
  db:
    container_name: fanddle-test-db
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    ports:
      - 5434:5432
    volumes:
      - ./database:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --port 6379
    restart: always
    ports:
      - 6380:6379
